name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DISABLE_AB_TESTING: 'true'
    steps:
      - uses: actions/checkout@v4
        with:
            path: langchain-starter
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: Genez-io/genezio-github-action@v1
        with:
          token: ${{ secrets.GENEZIO_PROD_TOKEN }}
      - name: Deploy backend
        working-directory: langchain-starter
        run: genezio deploy
